import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { GlobalProvider } from '@/providers/global.provider'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		// Ficar atento com o atributo suppressHydrationWarning que pode mascarar erros de hydration no futuro
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main>
					<GlobalProvider>{children}</GlobalProvider>
				</main>
			</body>
		</html>
	)
}
